# Generated by Django 4.1.5 on 2023-03-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companie',
        ),
    ]
