# Generated by Django 4.1.5 on 2023-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_company_companie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='29.99', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dairies', 'Dairies'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('fruits', 'Fruits'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('household items', 'Household items')], default=None, max_length=20),
        ),
    ]
