# Generated by Django 4.1.5 on 2023-03-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_price_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('employer_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.companie')),
            ],
        ),
    ]
