# Generated by Django 4.1.5 on 2023-03-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_marketer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketer',
        ),
    ]
