# Generated by Django 4.1.5 on 2023-03-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_product_marketer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketer',
        ),
    ]
